apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: scurrent/multi-worker
          env:
            - name: REDIS_HOST   #name of the redis cluster IP service
              value: redis-cluster-ip-service
            - name: REDIS_POST
              value: '6379'
